import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(__dirname, "../package.json"), "utf-8"));
const version = pkg.version;

writeFileSync(
  resolve(__dirname, "../src/version.ts"),
  `// Auto-generated by scripts/gen-version.mjs — DO NOT EDIT\nexport const VERSION = "${version}";\n`
);

console.log(`Generated src/version.ts with version ${version}`);